### ISSUE TITLE
Unable to navigate backwards from wallet page

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#104]
Once loading a wallet page, due to the way that sort params are added to the URL, it becomes impossible to navigate back from that page.

**Comment by willgarrett64** [comment]
This isn't restricted to the wallet page, and also doesn't appear related to the sorting. I believe it's due to the page clamping

https://github.com/edge/explorer/blob/86dcc9183766215c8d2556a52dd979e2aee0d154/src/views/Stakes.vue#L164

If you navigate to `/stakes`, it auto-navigates you to `/stakes?page=1`. Hitting back takes you back to `stakes`, which in turn re-auto-navigates you back to `/stakes?page=1`, and so on
